CREATE TABLE booktour (
	BookTourID INT(10) NOT NULL AUTO_INCREMENT,
	TourID INT(10) NOT NULL,
	TourName VARCHAR(1000) NOT NULL ,
	UserBookTour VARCHAR(100) NOT NULL ,
	EmailUser VARCHAR(100) NOT NULL ,
	AddressUser VARCHAR(2000) NOT NULL ,
	NumberPhoneUser VARCHAR(15) NOT NULL ,
	Status VARCHAR(10) NOT NULL ,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (BookTourID) 
);


CREATE TABLE item (
	ItemID INT(10) NOT NULL AUTO_INCREMENT,
	Type VARCHAR(20) NOT NULL ,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (ItemID) 
);


CREATE TABLE itemlibrary (
	ItemLibraryID INT(10) NOT NULL AUTO_INCREMENT,
	ItemID INT(10) NOT NULL,
	LibraryID INT(10) NULL DEFAULT NULL,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (ItemLibraryID) 
);


CREATE TABLE library (
	LibraryID INT(10) NOT NULL AUTO_INCREMENT,
	LibraryName VARCHAR(1000) NOT NULL ,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (LibraryID) 
);


CREATE TABLE locationandservice (
	LocationAndServiceID INT(10) NOT NULL AUTO_INCREMENT,
	MountaineeringID INT(10) NOT NULL,
	ServiceID INT(10) NOT NULL,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (LocationAndServiceID) 
);


CREATE TABLE member (
	MemberID INT(10) NOT NULL AUTO_INCREMENT,
	MemberName VARCHAR(45) NOT NULL ,
	Password VARCHAR(45) NOT NULL ,
	Role VARCHAR(45) NULL DEFAULT NULL ,
	Firstname VARCHAR(15) NOT NULL ,
	Middlename VARCHAR(15) NOT NULL ,
	Lastname VARCHAR(15) NOT NULL ,
	Birthday DATETIME NOT NULL,
	Sex VARCHAR(10) NOT NULL ,
	Telephone VARCHAR(20) NOT NULL ,
	Email VARCHAR(500) NOT NULL ,
	Status VARCHAR(45) NULL DEFAULT NULL ,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (MemberID) 
);


CREATE TABLE mountaineering (
	MountaineeringID INT(10) NOT NULL AUTO_INCREMENT,
	LocationX VARCHAR(100) NOT NULL ,
	LocationY VARCHAR(100) NOT NULL ,
	MountainName VARCHAR(1000) NOT NULL ,
	Level VARCHAR(20) NOT NULL ,
	Banner VARCHAR(2000) NOT NULL ,
	Type INT(10) NOT NULL,
	Sheltering VARCHAR(1000) NOT NULL ,
	Techniques VARCHAR(1000) NOT NULL ,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (MountaineeringID) 
);


CREATE TABLE news (
	NewsID INT(10) NOT NULL AUTO_INCREMENT,
	Title VARCHAR(1000) NOT NULL ,
	Content LONGTEXT NOT NULL ,
	AvatarNews VARCHAR(1000) NOT NULL ,
	Author VARCHAR(45) NOT NULL ,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (NewsID) 
);


CREATE TABLE service (
	ServiceID INT(10) NOT NULL AUTO_INCREMENT,
	ServiceName VARCHAR(1000) NOT NULL ,
	Price DECIMAL(10,0) NOT NULL,
	VAT INT(10) NOT NULL,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (ServiceID)
);


CREATE TABLE tour (
	TourID INT(10) NOT NULL AUTO_INCREMENT,
	TourName VARCHAR(1000) NOT NULL ,
	TimeStart DATETIME NOT NULL,
	TimeLimit VARCHAR(100) NOT NULL ,
	TourPrice DECIMAL(10,0) NOT NULL,
	TourSale DECIMAL(10,0) NULL DEFAULT NULL,
	Location VARCHAR(1000) NOT NULL ,
	AvatarTour VARCHAR(2000) NOT NULL ,
	Status VARCHAR(20) NOT NULL ,
	Description LONGTEXT NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (TourID) 
);


CREATE TABLE usersystem (
	UserSystemID INT(10) NOT NULL AUTO_INCREMENT,
	UserName VARCHAR(100) NOT NULL ,
	Password VARCHAR(500) NOT NULL ,
	Role VARCHAR(500) NULL DEFAULT NULL ,
	Description LONGTEXT NULL DEFAULT NULL ,
	Status VARCHAR(20) NULL DEFAULT NULL ,
	Flag VARCHAR(1) NULL DEFAULT NULL ,
	PRIMARY KEY (UserSystemID) 
);
